apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gavin-portfolio
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: hello-world  
    spec:     # pod spec                  
      containers: 
      - name: gavin-portfolio 
        image: gavin-portfolio
        ports:
        - containerPort: 3000